### ISSUE TITLE
problem with conda installation

### ISSUE THREAD

**Issue by asteindorff** [stajichlab/FGMP#12]
I installed the program using conda, but I get this error when I try to run:

> Can't locate FGMP.pm in @INC (you may need to install the FGMP module)

I tried to add the FGPM module in my @INC, no success.

**Comment by ocisse** [comment]
Thanks. It looks like something like the following code is missing in the bioconda recipe
`ln -s ${FGMP_HOME}/lib/FGMP.pm ${PREFIX}/lib/FGMP.pm`

here is a temporary fix:
`export PERL5LIB="$PERL5LIB:/Users/cisseoh/anaconda3/share/fgmp-1.0.3-0/lib"`

**Comment by hyphaltip** [comment]
Ill see if I can fix the recipe in bioconda thanks for the report.

Jason E Stajich, PhD
Professor and Director, Microbiology Graduate Program
Dept of Microbiology and Plant Pathology
University of California, Riverside
http://lab.stajich.org @stajichlab @hyphaltip @zygolife
+1 951.827.2363

**Comment by molecules** [comment]
My quick fix was going to path/to/lib/5.26.2 and creating a link, thus:

`ln -s path/to/share/fgmp-1.0.3-0/lib/FGMP.pm`

**Comment by hyphaltip** [comment]
thanks - I have not had a chance to make the conda fix but I can talk with
Brad there about making sure we do it correctly.

Jason E Stajich, PhD
Professor and Director, Microbiology Graduate Program
Department of Microbiology and Plant Pathology
University of California, Riverside
http://lab.stajich.org @stajichlab @hyphaltip @zygolife
+1 951.827.2363

**Comment by emmannaemeka** [comment]
Had similar issue  tried using the temporary fix export PERL5LIB="$PERL5LIB:/opt/anaconda3/envs/fgmp/sharefgmp-1.0.3-1/lib"

Error
Can't locate FGMP.pm in @INC (you may need to install the FGMP module) (@INC contains: /opt/anaconda3/envs/fgmp/bin/lib /opt/anaconda3/envs/fgmp/bin/../lib/5.26.2/darwin-thread-multi-2level /opt/anaconda3/envs/fgmp/bin/../lib/5.26.2 /opt/anaconda3/envs/fgmp/bin/../lib /Users/cisseoh/anaconda3/share/fgmp-1.0.3-0/lib /opt/anaconda3/envs/fgmp/sharefgmp-1.0.3-1/lib /opt/anaconda3/envs/fgmp/lib/site_perl/5.26.2/darwin-thread-multi-2level /opt/anaconda3/envs/fgmp/lib/site_perl/5.26.2 /opt/anaconda3/envs/fgmp/lib/5.26.2/darwin-thread-multi-2level /opt/anaconda3/envs/fgmp/lib/5.26.2 .) at /opt/anaconda3/envs/fgmp/bin/fgmp line 41.

**Comment by hyphaltip** [comment]
We will to get this fixed in conda.

Jason E Stajich, PhD
Professor and Director, Microbiology Graduate Program
Dept of Microbiology and Plant Pathology
University of California, Riverside

Fellow, CIFAR Fungal Kingdom: Threats & Opportunities
email: jason.stajich@ucr.edu
twitter: @stajichlab@hyphaltip@zygolife
website: lab.stajich.org
phone: +1 951.827.2363

**Comment by ocisse** [comment]
Sure - 

"Had similar issue tried using the temporary fix export PERL5LIB="$PERL5LIB:/opt/anaconda3/envs/fgmp/sharefgmp-1.0.3-1/lib""
Which system are you using? what happens if you copy the lib file in the directory where the main script is?
