### ISSUE TITLE
Problem with 'training augustus' step

### ISSUE THREAD

**Issue by hledbetter** [stajichlab/FGMP#13]
I just installed this program and am trying to run the sample file through, but keep running into issues with the 'training augustus' step. 
```
(fgmp) MBP-19-C02YPJ7PLVCF:FGMP NAME$ src/fgmp.pl -g sample/sample_test.dna NAME/Desktop/output
[ 27-06-2019 11:30:42 AM ]	found compressed file: /Users/NAME/FGMP/593_cleanMarkers.hmm.gz - decompressing ...
[ 27-06-2019 11:30:42 AM ]	Finding candidate regions
[ 27-06-2019 11:44:14 AM ]	Refining mapping on candidate regions
[ 27-06-2019 11:44:14 AM ]	Mapping proteins to assembly chunks using Exonerate
[ 27-06-2019 11:44:34 AM ]	Training Augustus
cannot execute	new_species.pl --species=sample/sample_test.dna --AUGUSTUS_CONFIG_PATH=/Users/NAME/FGMP/augustus_tmp/config > /dev/null 2>&1:No such file or directory at src/fgmp.pl line 262.
```
When I try to run the ```new_species.pl``` command independently, I get a 'could not write' error. I've checked and I have read/write permissions for that directory.
```
(fgmp) MBP-19-C02YPJ7PLVCF:FGMP NAME$ new_species.pl --species=sample/sample_test.dna --AUGUSTUS_CONFIG_PATH=/Users/NAME/FGMP/augustus_tmp/config
Will create parameters for a EUKARYOTIC species!
creating directory /Users/NAME/FGMP/augustus_tmp/config/species/sample/sample_test.dna/ ...
creating /Users/NAME/FGMP/augustus_tmp/config/species/sample/sample_test.dna/sample/sample_test.dna_parameters.cfg ...
Could not write /Users/NAME/FGMP/augustus_tmp/config/species/sample/sample_test.dna/sample/sample_test.dna_parameters.cfg. at /anaconda3/envs/fgmp/bin/new_species.pl line 115.
```
Any idea where I'm going wrong?

**Comment by ocisse** [comment]
I could not replicate this error, but it looks like you have a permission issue for that directory. Can you try to manually install fgmp as explained in the README? Let me know how it goes.

Thanks

**Comment by hyphaltip** [comment]
I agree it would be helpful to see permissions on

/Users/NAME/FGMP/augustus_tmp/config

and /Users/NAME/FGMP/augustus_tmp

(eg

ls -l /Users/NAME/FGMP/augustus_tmp/config )


Jason


---
Jason E Stajich, PhD
Professor and Director, Microbiology Graduate Program
Dept of Microbiology and Plant Pathology
University of California, Riverside

Fellow, CIFAR Fungal Kingdom: Threats & Opportunities
email: jason.stajich@ucr.edu
twitter: @stajichlab <http://twitter.com/stajichlab> @hyphaltip
<http://twitter.com/hyphaltip> @zygolife <http://twitter.com/zygolife>
website: http://lab.stajich.org
phone: +1 951.827.2363

**Comment by hledbetter** [comment]
I did the manual install following the directions in the README (including using augustus 3.2.3, since I'm working on a mac). Could re-install if that's helpful. As for permissions:
```
(fgmp) MBP-19-C02YPJ7PLVCF:FGMP NAME$ ls -l /Users/NAME/FGMP/augustus_tmp/config
total 0
drwxr-xr-x   8 NAME  staff  256 Jun 29 08:48 cgp
drwxr-xr-x  13 NAME  staff  416 Jun 29 08:48 extrinsic
drwxr-xr-x  27 NAME  staff  864 Jun 29 08:48 model
drwxr-xr-x   5 NAME  staff  160 Jun 29 08:48 profile
drwxr-xr-x   4 NAME  staff  128 Jun 29 08:48 species
(fgmp) MBP-19-C02YPJ7PLVCF:FGMP NAME$ ls -l /Users/NAME/FGMP/augustus_tmp
total 0
drwxr-xr-x  7 NAME  staff  224 Jun 29 08:48 config
```
Thanks,
Hannah

**Comment by hledbetter** [comment]
It looks like `new_species.pl` doesn't handle the file name having `/` in it very well, so moving the `sample_test.dna` file out of the `sample/` directory and into my home directory took care of it, ie:

`(fgmp) MBP-19-C02YPJ7PLVCF:FGMP NAME$ src/fgmp.pl -g sample_test.dna`

rather than

`(fgmp) MBP-19-C02YPJ7PLVCF:FGMP NAME$ src/fgmp.pl -g sample/sample_test.dna`
