### ISSUE TITLE
Running into issues with FGMP

### ISSUE THREAD

**Issue by sagnikbanerjee15** [stajichlab/FGMP#16]
Hello,

I have installed FGMP within a conda environment. The installation has succeeded but the test run fails. The command I have used is: 

```
nohup src/fgmp.pl -g sample/sample_test.dna -T 30 --tag OMA -o fgmp_test > fgmp_test.output 2> fgmp_test.error
```

The error I am getting is:

```
[ 11-04-2020 06:21:16 AM ]	file: /work/LAS/rpwise-lab/sagnik/softwares/FGMP/data/593_cleanMarkers.hmm.gz is already decompressed - good!
[ 11-04-2020 06:21:16 AM ]	Finding candidate regions
[ 11-04-2020 06:21:20 AM ]	Refining mapping on candidate regions
[ 11-04-2020 06:21:20 AM ]	Training Augustus
cannot execute	new_species.pl --species=sample/sample_test.dna --AUGUSTUS_CONFIG_PATH=/work/LAS/rpwise-lab/sagnik/softwares/FGMP/augustus_tmp/config > /dev/null 2>&1:
 at src/fgmp.pl line 262.
```

I have executed the line

```
new_species.pl --species=sample/sample_test.dna --AUGUSTUS_CONFIG_PATH=/work/LAS/rpwise-lab/sagnik/softwares/FGMP/augustus_tmp/config > /dev/null 2>&1
```

This run completes successfully but does not produce any results.

Please help.

Thank you.

**Comment by ocisse** [comment]
Hah! I've seen this before. Try another fasta and move ii the current dir. let me know how it goes. Thanks

**Comment by sagnikbanerjee15** [comment]
Hello,

I tried with a different fasta file but it gave me the same error. I am not completely sure which current directory you are talking about. I ran it from within the FGMP directory.

Thanks.

**Comment by ocisse** [comment]
Ok. Can try "new_species.pl" without "> /dev/null 2>&1". Hopefully, it will tell you what's wrong. If the problem persists install Augustus separately and make sure these tools available are available in the standard path (e.g. ln -s /usr/local/bin/). 

Thanks

**Comment by sagnikbanerjee15** [comment]
Thanks for your reply.

I executed the new_species.pl command as you directed and this is the error I received.

```
Will create parameters for a EUKARYOTIC species!
creating directory /work/LAS/rpwise-lab/sagnik/softwares/FGMP/augustus_tmp/config/species/sample/sample_test.dna/ ...
creating /work/LAS/rpwise-lab/sagnik/softwares/FGMP/augustus_tmp/config/species/sample/sample_test.dna/sample/sample_test.dna_parameters.cfg ...
Could not write /work/LAS/rpwise-lab/sagnik/softwares/FGMP/augustus_tmp/config/species/sample/sample_test.dna/sample/sample_test.dna_parameters.cfg. at /work/LAS/rpwise-lab/sagnik/softwares/anaconda3/envs/FGMP/bin/new_species.pl line 115.
```

I checked and found that the directory /work/LAS/rpwise-lab/sagnik/softwares/FGMP/augustus_tmp/config/species/sample was not created.

Thank you.
