### ISSUE TITLE
Problems encountered with tblastn

### ISSUE THREAD

**Issue by Ph0Ph0Q** [stajichlab/FGMP#17]
Hello, I have some troubles with using FGMP :

When I run "fgmp -g Gd293_Minion_canu.contigs.fasta -T 20 fgmp_report.out", my console prints this error:
[ 09-05-2020 01:52:31  ]	file: /media/bigvol/matthieuf/data/minion/Assemblies/data/593_cleanMarkers.hmm.gz is already decompressed - good!
[ 09-05-2020 01:52:31  ]	Finding candidate regions
Segmentation fault
cannot execute	tblastn -db Gd293_Minion_canu.contigs.fasta.db -query /media/bigvol/matthieuf/data/minion/Assemblies/data/593_cleanMarkers.fa -word_size 5 -max_target_seqs 5 -evalue 0.01 -seg yes -num_threads 20 -outfmt  "7 sseqid sstart send sframe bitscore qseqid" > Gd293_Minion_canu.contigs.fasta.tblastn:No such file or directory
 at /media/bigvol/matthieuf/miniconda3/envs/fgmp_env/bin/fgmp line 441.

But when I do "ls" in my directory, the file “Gd293_Minion_canu.contigs.fasta.tblastn” exists and is not empty.

So I tried to run again tblastn alone, to check whether to problem comes from FGMP or tblastn , and I have the same error:

tblastn -db Gd293_Minion_canu.contigs.fasta.db -query /media/bigvol/matthieuf/data/minion/Assemblies/data/593_cleanMarkers.fa -word_size 5 -max_target_seqs 5 -evalue 0.01 -seg yes -num_threads 20 -outfmt  "7 sseqid sstart send sframe bitscore qseqid" > Gd293_Minion_canu.contigs.fasta.tblastn
Segmentation fault

Can the problems comes from the way FGMP creates blast databases? 

Sometimes I have some other errors (when I use the path of my contig file):

[ 09-05-2020 03:09:46  ]	file: /media/bigvol/matthieuf/data/minion/Assemblies/data/593_cleanMarkers.hmm.gz is already decompressed - good!
[ 09-05-2020 03:09:46  ]	Finding candidate regions
[ 09-05-2020 03:29:45  ]	Refining mapping on candidate regions
Can't open file '/media/bigvol/matthieuf/data/minion/Assemblies//media/bigvol/matthieuf/data/minion/Assemblies/Gd293_Minion_canu.contigs.fasta.candidates.fa.chunk0.tmp' for output:
No such file or directory at /media/bigvol/matthieuf/miniconda3/envs/fgmp_env/lib/site_perl/5.26.2/FGMP.pm line 158.

I really don't understand why I have these errors, could you help me please?

Thank you 

Matthieu
Fournel

**Comment by ocisse** [comment]
Hi Matthieu
```
tblastn -db Gd293_Minion_canu.contigs.fasta.db -query /media/bigvol/matthieuf/data/minion/Assemblies/data/593_cleanMarkers.fa -word_size 5 -max_target_seqs 5 -evalue 0.01 -seg yes -num_threads 20 -outfmt "7 sseqid sstart send sframe bitscore qseqid" > Gd293_Minion_canu.contigs.fasta.tblastn
Segmentation fault
```
The seg fault signal means that BLAST is trying to access a memory location that isn't available. Did you install FGMP with conda? Then it should come with a proper BLAST version. Alternatively, you might want to check if BLAST running properly on your system first. 

```[ 09-05-2020 03:09:46 ] file: /media/bigvol/matthieuf/data/minion/Assemblies/data/593_cleanMarkers.hmm.gz is already decompressed - good!
[ 09-05-2020 03:09:46 ] Finding candidate regions
[ 09-05-2020 03:29:45 ] Refining mapping on candidate regions
Can't open file '/media/bigvol/matthieuf/data/minion/Assemblies//media/bigvol/matthieuf/data/minion/Assemblies/Gd293_Minion_canu.contigs.fasta.candidates.fa.chunk0.tmp' for output:
No such file or directory at /media/bigvol/matthieuf/miniconda3/envs/fgmp_env/lib/site_perl/5.26.2/FGMP.pm line 158.
```
Here FGMP simply skipped  BLAST because the file is present and doesn't looks damaged. Can you please check if you have rights the write files on the directory (may be you need admin privileges?).

Let me know how it goes and thank you very much for using fg!

Ousmane
