### ISSUE TITLE
Some documentation needed on report outputs

### ISSUE THREAD

**Issue by mglgc** [stajichlab/FGMP#22]
Dear FGMP developers,

The report output files (mainly the summary report) contains some acrostics and abbreviated words, e.g. UCEs, fUCES. OHC, JES, and so on, making pretty difficult to get a right understanding of the real differences between several genomes to compare. No clues are made about this in the the orginal paper. Also, what do the different percent figures refer to, i.e. what percent figure should be used to compare completeness between different genomes?
Thank you very much in advance for your reply.

**Comment by ocisse** [comment]
Hi, 
For completeness estimation please use the percentage below in your report

```
(example)
NUM OF FGMP COMPLETENESS MARKERS:	210
Estimate completeness:	85.7 (%)
```

Then have a look at the conserved elements. This is informative but it might differ from proteins-based estimation (see https://doi.org/10.1186/s12859-019-2782-9). 

The acronyms:
```
UCEs: ultra conserved elements
fUCEs: fungal ultra conserved elements

Authors:
OHC: (my name): Ousmane H. Cisse
JES: Jason E. Stajich
```

Happy to discuss further if needed

Thanks

**Comment by mglgc** [comment]
Dear Ousmane,
Thanks a lot for your prompt, very informative reply. The summary reports are more clear and useful now.
Just one question about --tag options. OMA is among them but the original paper refers that this database is used in the normal FGMP workflow, so what is the meaning of such a --tag option?
Thank you so much.

**Comment by ocisse** [comment]
This is a legacy option originally intended to differentiate makers derived from orthologs identified using OMA (https://omabrowser.org/oma/home/) from those of CEGMA (http://korflab.ucdavis.edu/datasets/cegma/) and FunyBASE (http://genome.jouy.inra.fr/funybase/). However, both CEGMA and FUN were discontinued, this option will (likely) be depreciated in the future.

Thanks for using fg
